### ISSUE TITLE
help

### ISSUE THREAD

**Issue by UchihaSR** [serdeliuk/VirtualBiosMod#3]
i would like to tell you that this issue is not related to the project. but i saw your issue on cloverbootloader repo, and i would like to ask you how did you compile the bootloader. i am failing to do so. i had my issue closed down in that repo.  your help will be appreciated.

**Comment by serdeliuk** [comment]
Please ask questions related to CloverBootloader on their issues tickets, this way may other take advantage on the answers too. I think i already updated that thread saing how i was able to compile, if you need more details just ask there an i or others will respond

**Comment by serdeliuk** [comment]
> i would like to tell you that this issue is not related to the project. but i saw your issue on cloverbootloader repo, and i would like to ask you how did you compile the bootloader. i am failing to do so. i had my issue closed down in that repo. your help will be appreciated.

on short i was able to compile a good Clover wihch boot too on Mojave with Xcode11 and command line tools, then downloaded clover repo `git clone --recurse-submodules  https://github.com/CloverHackyColor/CloverBootloader` please note --recurse-submodules parameter :)
Then use `. ./edksetup.sh` or `source ./edksetup.sh` then `buildme` and chose 1 in the menu
