### ISSUE TITLE
Asus ROG GL502VSK

### ISSUE THREAD

**Issue by Dry05** [serdeliuk/VirtualBiosMod#4]
Hey, sorry if this is the wrong place for this. But could you please bring support for the GL502VSK? It would be awesome to use on that model

**Comment by serdeliuk** [comment]
Hi, what kind of mods are you interested in? Did you read the wiki? If you know a bit of programming you can do it yourself.
I can build a special version for your Asus, but will take a while as i am very busy those days.

**Comment by Dry05** [comment]
I would be interested in disabling my Gtx 1070 so I can run on my intel graphics

**Comment by serdeliuk** [comment]
Ok, i will try to build a vbm for your notebook too, please ask for this the in thread from the readme or wiki, i will share there the vbm version to test, if works i will publish the complete version on github.
