### ISSUE TITLE
Feature request: Add options to ajust VRAM for more than 2GB, and update the source code to follow the latest.

### ISSUE THREAD

**Issue by dunghoilyd01** [serdeliuk/VirtualBiosMod#5]
It's been a long time. I hope that you can add more options to adjust iGPU VRAM to be 4GB or maybe more. And please update the source code to match the latest version. Thanks.

**Comment by serdeliuk** [comment]
Hi, the "Press F to loop through all memory sizes" in the latest release does what you need if i recall right, i am a bit busy those days, i will try to update the source code to the my latest work. The VRAM sizes are predefined without modification options. 128MB, 256MB, 512M, 1024MB and 2048MB

**Comment by dunghoilyd01** [comment]
Thanks for your information. I'm using KVM on linux with Intel GVT-g passthrough to work with VMs. since every VMs created it reserve its own VRAM so i want a larger options (4096MB maybe). Thanks for quick reply, GL on you work.

**Comment by serdeliuk** [comment]
Extract your BIOS variables into a readable text file (check VBM wiki for how to do this) and check for your bios setting, my version allow max 2048MB.
Search in your text file for "Aperture Size" and see what options your firmware have, i think my latest test was done with 3.0.5 firmware

**Comment by dunghoilyd01** [comment]
Thanks for you tip, i will try, but maybe it should be the same to you cuz my laptop is G531GT with BIOS version 300.

**Comment by serdeliuk** [comment]
You can try to download the latest update from Asus and extract from that and see if they increased the size option, if so worth to upgrade and use VBM to mod this

**Comment by dunghoilyd01** [comment]
Can't compile amifldrv because of the kernel. Do you remember which kernel version have you used? Are the any alternative software for this?

**Comment by serdeliuk** [comment]
I think you don't need that part as you already have the bios from the update package, you only need the UEFItool and ifrextract to run them on your downloaded firmare

**Comment by serdeliuk** [comment]
And this too :)
`https://github.com/platomav/BIOSUtilities/blob/master/AMI%20BIOS%20Guard%20Extractor/AMI_PFAT_Extract.py`

**Comment by dunghoilyd01** [comment]
0x37CB1 		One Of: Aperture Size, VarStoreInfo (VarOffset/VarName): 0x962, VarStore: 0x1, QuestionId: 0x2746, Size: 1, Min: 0x0, Max 0xF, Step: 0x0 {05 91 AB 06 AC 06 46 27 01 00 62 09 14 10 00 0F 00}
0x37CC2 			One Of Option: 128MB, Value (8 bit): 0x0 {09 07 AD 06 00 00 00}
0x37CC9 			One Of Option: 256MB, Value (8 bit): 0x1 (default) {09 07 AE 06 30 00 01}
0x37CD0 			One Of Option: 512MB, Value (8 bit): 0x3 {09 07 AF 06 00 00 03}
0x37CD7 			One Of Option: 1024MB, Value (8 bit): 0x7 {09 07 B0 06 00 00 07}
0x37CDE 			One Of Option: 2048MB, Value (8 bit): 0xF {09 07 B1 06 00 00 0F}
0x37CE5 		End One Of {29 02}

I can do nothing, haha. Thanks for helping me alot. I will close this issue because i think my problem is solved.

**Comment by serdeliuk** [comment]
You're quite welcome, Thank you too for let me know your testing env, what firmware version is that, the latest one?
At least you can rise to 2048MB from 256MB(Default)

I think a hardware firmware mod can rise those values, you can try win-raid or bios-mods forums, ask them, who knows, maybe there are other settings we can tweak too

**Comment by dunghoilyd01** [comment]
I've extracted the value from the old firmware (300)  and the latest one(308). But it still provide the same maximum value (2048MB). 
I use Intel GVT-g in KVM on Linux. The exact value of VRAM can be seen with lspci -vv -s 00:02.0,  in the line begin with Region 2:.
